generate_textual_report <- function(selected, dtxsids, chemical_name){
    # Generate textual PDF reports per chemical specifically for use with RAG LLMs
    annotations <- llm_annotations(selected, dtxsids)
    
    # admet_binr <- as.data.frame(annotations[["anno_admet_binr"]])
    # admet_catg <- as.data.frame(annotations[["anno_admet_catg"]])
    # admet_cont <- as.data.frame(annotations[["anno_admet_cont"]])
    # 
    chembl <- as.data.frame(annotations[["anno_chembl"]])
    # 
    # cpd <- as.data.frame(annotations[["anno_cpd"]])
    # 
    # ctd_bioprocess <- as.data.frame(annotations[["anno_ctd_bioprocess"]])
    # ctd_cellcomp <- as.data.frame(annotations[["anno_ctd_cellcomp"]])
    # ctd_diseases <- as.data.frame(annotations[["anno_ctd_diseases"]])
    # ctd_genes <- as.data.frame(annotations[["anno_ctd_genes"]])
    # ctd_molfunct <- as.data.frame(annotations[["anno_ctd_molfunct"]])
    # ctd_phenotypes <- as.data.frame(annotations[["anno_ctd_phenotypes"]])
    # 
    # drugbank_atccodes <- as.data.frame(annotations[["anno_drugbank_atccodes"]])
    # drugbank_carriers <- as.data.frame(annotations[["anno_drugbank_carriers"]])
    # drugbank_enzymes <- as.data.frame(annotations[["anno_drugbank_enzymes"]])
    # drugbank_targets <- as.data.frame(annotations[["anno_drugbank_targets"]])
    # drugbank_transporters <- as.data.frame(annotations[["anno_drugbank_transporters"]])
    # 
    # hmdb_biospecimenlocations <- as.data.frame(annotations[["anno_hmdb_biospecimenlocations"]])
    # hmdb_cellularlocations <- as.data.frame(annotations[["anno_hmdb_cellularlocations"]])
    # hmdb_diseases <- as.data.frame(annotations[["anno_hmdb_diseases"]])
    # hmdb_genes <- as.data.frame(annotations[["anno_hmdb_genes"]])
    # hmdb_tissuelocations <- as.data.frame(annotations[["anno_hmdb_tissuelocations"]])
    # 
    # ice <- as.data.frame(annotations[["anno_ice"]]) #TODO - this is complicated
    # 
    # invitrodb <- as.data.frame(annotations[["anno_invitrodb"]]) #TODO - this is complicated
    # 
    # leadscope <- as.data.frame(annotations[["anno_leadscope"]])
    # 
    # ochem <- as.data.frame(annotations[["anno_ochem"]])
    # 
    # opera_adme <- as.data.frame(annotations[["anno_opera_adme"]])
    # opera_environmental_fate <- as.data.frame(annotations[["anno_opera_environmental_fate"]])
    # opera_physicochem <- as.data.frame(annotations[["anno_opera_physicochem"]])
    # opera_structural_properties <- as.data.frame(annotations[["anno_opera_structural_properties"]])
    # opera_toxicology_endpoints <- as.data.frame(annotations[["anno_opera_toxicology_endpoints"]])
    # 
    # saagar <- as.data.frame(annotations[["anno_saagar"]])
    # 
    # t3db <- as.data.frame(annotations[["anno_t3db"]])
    # 
    # toxrefdb_neoplastic <- as.data.frame(annotations[["anno_toxrefdb_neoplastic"]])
    # toxrefdb_nonneoplastic <- as.data.frame(annotations[["anno_toxrefdb_nonneoplastic"]])
    # 
    # pubchem_bioassays <- as.data.frame(annotations[["anno_pubchem"]])
    #pubchem_props <- as.data.frame(annotations[["anno_pubchem_props"]])
    # 
    # gras <- as.data.frame(annotations[["anno_gras"]])
    # 
    # foodb_enzymes <- as.data.frame(annotations[["anno_foodb_enzymes"]])
    # foodb_flavors <- as.data.frame(annotations[["anno_foodb_flavors"]])
    # foodb_foodcontent <- as.data.frame(annotations[["anno_foodb_foodcontent"]])
    # foodb_healtheffects <- as.data.frame(annotations[["anno_foodb_healtheffects"]])
    # foodb_ontology <- as.data.frame(annotations[["anno_foodb_ontology"]])
    
    #epa_props <- as.data.frame(annotations[["anno_epa_props"]]) #TODO
    # print(epa_props)
    
    # ### ADMET MODELS ###
    # text_admet_binr <- paste0("The following are predictions for ", chemical_name, " using ADMET QSAR predictive models. These models generate binary output. The output may be either positive, negative, or not in domain. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_admet_binr2 <- apply(admet_binr, 1, function(x){
    #     paste0(x["model"], " - ", x["description"], ": ", if(x["value"] == 1) "positive" else if(x["value"] == 0) "negative" else "not in domain")
    # })
    # text_admet_binr <- paste0(text_admet_binr, "\n\n", paste0(text_admet_binr2, collapse="\n"))
    # writeLines(text_admet_binr, paste0("./reports/admet_binr__", dtxsids, ".txt"))
    # 
    # text_admet_catg <- paste0("The following are predictions for ", chemical_name, " using ADMET QSAR predictive models. These models generate categorical output. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_admet_catg2 <- apply(admet_catg, 1, function(x){
    #     paste0(x["model"], " - ", x["description"], ": ", x["value"])
    # })
    # text_admet_catg <- paste0(text_admet_catg, "\n\n", paste0(text_admet_catg2, collapse="\n"))
    # writeLines(text_admet_catg, paste0("./reports/admet_catg__", dtxsids, ".txt"))
    # 
    # 
    # text_admet_cont <- paste0("The following are predictions for ", chemical_name, " using ADMET QSAR predictive models. These models generate continuous output. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_admet_cont2 <- apply(admet_cont, 1, function(x){
    #     paste0(x["model"], " - ", x["description"], ": ", x["value"])
    # })
    # text_admet_cont <- paste0(text_admet_cont, "\n\n", paste0(text_admet_cont2, collapse="\n"))
    # writeLines(text_admet_cont, paste0("./reports/admet_cont__", dtxsids, ".txt"))
    # 
    # ### CHEMBL ###
    print(chembl)
    text_chembl <- paste0("The following are various chemical structural features present in ChEMBL, and if they are present in the chemical ", chemical_name, ". Each entry in the list is given as: [feature name] | [SMARTS]: [presence]. This report was automatically generated by ChemBioTox.")
    text_chembl2 <- apply(chembl, 1, function(x){
        paste0(x["feature"], ": ", if(x["present"] == 1) "present" else "not present")
    })
    text_chembl <- paste0(text_chembl, "\n\n", paste0(text_chembl2, collapse="\n"))
    writeLines(text_chembl, paste0("./reports/chembl__", dtxsids, ".txt"))
    # 
    # ### CPD ###
    # text_cpd <- paste0("The following are various commercially-available products that the chemical ", chemical_name, " may be found in, according to the Chemical Products Database (CPDat). Each entry in the list is given as: [general category] | [product family]: [product type]. This report was automatically generated by ChemBioTox.")
    # text_cpd2 <- apply(cpd, 1, function(x){
    #     paste0(x["gen_cat"], " | ", x["prod_fam"], " | ", x["prod_type"])
    # })
    # text_cpd <- paste0(text_cpd, "\n\n", paste0(text_cpd2, collapse="\n"))
    # writeLines(text_cpd, paste0("./reports/cpd__", dtxsids, ".txt"))
    # 
    # ### CTD ###
    # text_ctd_bioprocess <- paste0("The following are various biological processes that the chemical ", chemical_name, " may be associated with, according to the Comparative Toxicogenomics Database (CTD). This report was automatically generated by ChemBioTox.")
    # text_ctd_bioprocess2 <- apply(ctd_bioprocess, 1, function(x){
    #     paste0(chemical_name, " may be associated with ", x["go_term_name"], " (corrected pvalue: ", x["corrected_pvalue"], ").")
    # })
    # text_ctd_bioprocess <- paste0(text_ctd_bioprocess, "\n\n", paste0(text_ctd_bioprocess2, collapse="\n"))
    # writeLines(text_ctd_bioprocess, paste0("./reports/ctd_bioprocess__", dtxsids, ".txt"))
    # 
    # text_ctd_cellcomp <- paste0("The following are various cellular components that the chemical ", chemical_name, " may be associated with, according to the Comparative Toxicogenomics Database (CTD). This report was automatically generated by ChemBioTox.")
    # text_ctd_cellcomp2 <- apply(ctd_cellcomp, 1, function(x){
    #     paste0(chemical_name, " may be associated with ", x["go_term_name"], " (corrected pvalue: ", x["corrected_pvalue"], ").")
    # })
    # text_ctd_cellcomp <- paste0(text_ctd_cellcomp, "\n\n", paste0(text_ctd_cellcomp2, collapse="\n"))
    # writeLines(text_ctd_cellcomp, paste0("./reports/ctd_cellcomp__", dtxsids, ".txt"))
    # 
    # 
    # text_ctd_diseases <- paste0("The following are various diseases that the chemical ", chemical_name, " may be associated with, according to the Comparative Toxicogenomics Database (CTD). This report was automatically generated by ChemBioTox.")
    # text_ctd_diseases2 <- apply(ctd_diseases, 1, function(x){
    #     if(!is.na(x["direct_evidence"])){
    #         return(paste0(chemical_name, " is associated with ", x["disease_name"], " based on the following direct evidence: ", x["direct_evidence"], ". (source PMIDs: ", x["pubmed_ids"], ")"))
    #     }
    #     return(paste0(chemical_name, " may be associated with ", x["disease_name"], " based on its interactions with : ", x["inference_gene_symbol"], " (inference score: ", as.numeric(x["inference_score"]), "). (source PMIDs: ", x["pubmed_ids"], ")"))
    # })
    # text_ctd_diseases <- paste0(text_ctd_diseases, "\n\n", paste0(text_ctd_diseases2, collapse="\n"))
    # writeLines(text_ctd_diseases, paste0("./reports/ctd_diseases__", dtxsids, ".txt"))
    # 
    # 
    # text_ctd_genes <- paste0("The following are various genes that the chemical ", chemical_name, " may be associated with, according to the Comparative Toxicogenomics Database (CTD). This report was automatically generated by ChemBioTox.")
    # text_ctd_genes2 <- apply(ctd_genes, 1, function(x){
    #     paste0(x["interaction"], " in ", x["organism"], ". (source PMIDs: ", x["pubmed_ids"], ")")
    # })
    # text_ctd_genes <- paste0(text_ctd_genes, "\n\n", paste0(text_ctd_genes2, collapse="\n"))
    # writeLines(text_ctd_genes, paste0("./reports/ctd_genes__", dtxsids, ".txt"))
    # 
    # text_ctd_molfunct <- paste0("The following are various molecular functions that the chemical ", chemical_name, " may be associated with, according to the Comparative Toxicogenomics Database (CTD). This report was automatically generated by ChemBioTox.")
    # text_ctd_molfunct2 <- apply(ctd_molfunct, 1, function(x){
    #     paste0(chemical_name, " may be associated with ", x["go_term_name"], " (corrected pvalue: ", x["corrected_pvalue"], ").")
    # })
    # text_ctd_molfunct <- paste0(text_ctd_molfunct, "\n\n", paste0(text_ctd_molfunct2, collapse="\n"))
    # writeLines(text_ctd_molfunct, paste0("./reports/ctd_molfunct__", dtxsids, ".txt"))
    # 
    # text_ctd_phenotypes <- paste0("The following are various phenotypes that the chemical ", chemical_name, " may be associated with, according to the Comparative Toxicogenomics Database (CTD). This report was automatically generated by ChemBioTox.")
    # text_ctd_phenotypes2 <- apply(ctd_phenotypes, 1, function(x){
    #     paste0(x["interaction"], " in ", x["organism"], ". (source PMIDs: ", x["pubmed_ids"], ")")
    # })
    # text_ctd_phenotypes <- paste0(text_ctd_phenotypes, "\n\n", paste0(text_ctd_phenotypes2, collapse="\n"))
    # writeLines(text_ctd_phenotypes, paste0("./reports/ctd_phenotypes__", dtxsids, ".txt"))
    # 
    # ### DRUGBANK ###
    # text_drugbank_atccodes <- paste0("The following are various ATC codes that the chemical ", chemical_name, " may be associated with, according to DrugBank. This report was automatically generated by ChemBioTox.")
    # text_drugbank_atccodes2 <- apply(drugbank_atccodes, 1, function(x){
    #     paste0(chemical_name, " is associated with ", x["atc_annotation"], " (ATC code: ", x["atc_code"], ").")
    # })
    # text_drugbank_atccodes <- paste0(text_drugbank_atccodes, "\n\n", paste0(text_drugbank_atccodes2, collapse="\n"))
    # writeLines(text_drugbank_atccodes, paste0("./reports/drugbank_atccodes__", dtxsids, ".txt"))
    # 
    # 
    # text_drugbank_carriers <- paste0("The following are various carriers that the chemical ", chemical_name, " may be associated with, according to DrugBank. This report was automatically generated by ChemBioTox.")
    # text_drugbank_carriers2 <- apply(drugbank_carriers, 1, function(x){
    #     paste0(chemical_name, " is associated with the carrier ", x["annotation"])
    # })
    # text_drugbank_carriers <- paste0(text_drugbank_carriers, "\n\n", paste0(text_drugbank_carriers2, collapse="\n"))
    # writeLines(text_drugbank_carriers, paste0("./reports/drugbank_carriers__", dtxsids, ".txt"))
    # 
    # 
    # text_drugbank_enzymes <- paste0("The following are various enzymes that the chemical ", chemical_name, " may be associated with, according to DrugBank. This report was automatically generated by ChemBioTox.")
    # text_drugbank_enzymes2 <- apply(drugbank_enzymes, 1, function(x){
    #     paste0(chemical_name, " is associated with the enzyme ", x["annotation"])
    # })
    # text_drugbank_enzymes <- paste0(text_drugbank_enzymes, "\n\n", paste0(text_drugbank_enzymes2, collapse="\n"))
    # writeLines(text_drugbank_enzymes, paste0("./reports/drugbank_enzymes__", dtxsids, ".txt"))
    # 
    # 
    # text_drugbank_targets <- paste0("The following are various targets that the chemical ", chemical_name, " may be associated with, according to DrugBank. This report was automatically generated by ChemBioTox.")
    # text_drugbank_targets2 <- apply(drugbank_targets, 1, function(x){
    #     paste0(chemical_name, " has the target ", x["annotation"])
    # })
    # text_drugbank_targets <- paste0(text_drugbank_targets, "\n\n", paste0(text_drugbank_targets2, collapse="\n"))
    # writeLines(text_drugbank_targets, paste0("./reports/drugbank_targets__", dtxsids, ".txt"))
    # 
    # text_drugbank_transporters <- paste0("The following are various transporter proteins that the chemical ", chemical_name, " may be associated with, according to DrugBank. This report was automatically generated by ChemBioTox.")
    # text_drugbank_transporters2 <- apply(drugbank_transporters, 1, function(x){
    #     paste0(chemical_name, " is associated with the transporter protein ", x["annotation"])
    # })
    # text_drugbank_transporters <- paste0(text_drugbank_transporters, "\n\n", paste0(text_drugbank_transporters2, collapse="\n"))
    # writeLines(text_drugbank_transporters, paste0("./reports/drugbank_transporters__", dtxsids, ".txt"))
    # 
    # 
    # ### HMDB ###
    # text_hmdb_biospecimenlocations <- paste0("The following are various biological specimen locations that the chemical ", chemical_name, " may be found in, according to the Human Metabolome Database (HMDB). This report was automatically generated by ChemBioTox.")
    # text_hmdb_biospecimenlocations2 <- apply(hmdb_biospecimenlocations, 1, function(x){
    #     paste0(chemical_name, " is found in the ", x["annotation"])
    # })
    # text_hmdb_biospecimenlocations <- paste0(text_hmdb_biospecimenlocations, "\n\n", paste0(text_hmdb_biospecimenlocations2, collapse="\n"))
    # writeLines(text_hmdb_biospecimenlocations, paste0("./reports/hmdb_biospecimenlocations__", dtxsids, ".txt"))
    # 
    # 
    # text_hmdb_cellularlocations <- paste0("The following are various cellular locations that the chemical ", chemical_name, " may be found in, according to the Human Metabolome Database (HMDB). This report was automatically generated by ChemBioTox.")
    # text_hmdb_cellularlocations2 <- apply(hmdb_cellularlocations, 1, function(x){
    #     paste0(chemical_name, " is found in the ", x["annotation"])
    # })
    # text_hmdb_cellularlocations <- paste0(text_hmdb_cellularlocations, "\n\n", paste0(text_hmdb_cellularlocations2, collapse="\n"))
    # writeLines(text_hmdb_cellularlocations, paste0("./reports/hmdb_cellularlocations__", dtxsids, ".txt"))
    # 
    # text_hmdb_diseases <- paste0(chemical_name, " may be associated with the following diseases according to the Human Metabolome Database (HMDB). This report was automatically generated by ChemBioTox.")
    # text_hmdb_diseases2 <- apply(hmdb_diseases, 1, function(x){
    #     paste0(chemical_name, " is associated with the disease: ", x["annotation"])
    # })
    # text_hmdb_diseases <- paste0(text_hmdb_diseases, "\n\n", paste0(text_hmdb_diseases2, collapse="\n"))
    # writeLines(text_hmdb_diseases, paste0("./reports/hmdb_diseases__", dtxsids, ".txt"))
    # 
    # text_hmdb_genes <- paste0(chemical_name, " may be associated with the following genes according to the Human Metabolome Database (HMDB). This report was automatically generated by ChemBioTox.")
    # text_hmdb_genes2 <- apply(hmdb_genes, 1, function(x){
    #     paste0(chemical_name, " is associated with the gene: ", x["annotation"])
    # })
    # text_hmdb_genes <- paste0(text_hmdb_genes, "\n\n", paste0(text_hmdb_genes2, collapse="\n"))
    # writeLines(text_hmdb_genes, paste0("./reports/hmdb_genes__", dtxsids, ".txt"))
    # 
    # 
    # text_hmdb_tissuelocations <- paste0(chemical_name, " may be located in the following tissues according to the Human Metabolome Database (HMDB). This report was automatically generated by ChemBioTox.")
    # text_hmdb_tissuelocations2 <- apply(hmdb_tissuelocations, 1, function(x){
    #     paste0(chemical_name, " is found in ", x["annotation"])
    # })
    # text_hmdb_tissuelocations <- paste0(text_hmdb_tissuelocations, "\n\n", paste0(text_hmdb_tissuelocations2, collapse="\n"))
    # writeLines(text_hmdb_tissuelocations, paste0("./reports/hmdb_tissuelocations__", dtxsids, ".txt"))
    # 
    # ### LEADSCOPE MODELS ###
    # text_leadscope <- paste0("The following are predictions for ", chemical_name, " using Leadscope's QSAR predictive models from Instem. These models generate binary output. The output may be either positive, negative, or not in domain. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_leadscope2 <- apply(leadscope, 1, function(x){
    #     paste0(x["model_name"], " - ", x["short_description"], ": ", if(x["interpretation"] == 1) "positive" else if(x["interpretation"] == 0) "negative" else "not in domain")
    # })
    # text_leadscope <- paste0(text_leadscope, "\n\n", paste0(text_leadscope2, collapse="\n"))
    # writeLines(text_leadscope, paste0("./reports/leadscope__", dtxsids, ".txt"))
    # 
    # ### OChem ###
    # text_ochem <- paste0("The following are chemical alerts for ", chemical_name, " according to OChem. This report was automatically generated by ChemBioTox.")
    # text_ochem2 <- apply(ochem, 1, function(x){
    #     paste0(chemical_name, " has the alert: ", x["alert_name"])
    # })
    # text_ochem <- paste0(text_ochem, "\n\n", paste0(text_ochem2, collapse="\n"))
    # writeLines(text_ochem, paste0("./reports/ochem__", dtxsids, ".txt"))
    # 
    # ### Opera ###
    # text_opera_adme <- paste0("The following are predictions for ", chemical_name, " using ADME QSAR models available in Opera. These models generate output in a variety of formats. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_opera_adme2 <- apply(opera_adme, 1, function(x){
    #     paste0(x["model_name"], " - ", x["model_description"], ": ", x["model_value"])
    # })
    # text_opera_adme <- paste0(text_opera_adme, "\n\n", paste0(text_opera_adme2, collapse="\n"))
    # writeLines(text_opera_adme, paste0("./reports/opera_adme__", dtxsids, ".txt"))
    # 
    # 
    # text_opera_environmental_fate <- paste0("The following are predictions for ", chemical_name, " using environmental fate QSAR models available in Opera. These models generate output in a variety of formats. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_opera_environmental_fate2 <- apply(opera_environmental_fate, 1, function(x){
    #     paste0(x["model_name"], " - ", x["model_description"], ": ", x["model_value"])
    # })
    # text_opera_environmental_fate <- paste0(text_opera_environmental_fate, "\n\n", paste0(text_opera_environmental_fate2, collapse="\n"))
    # writeLines(text_opera_environmental_fate, paste0("./reports/opera_environmental_fate__", dtxsids, ".txt"))
    # 
    # 
    # text_opera_physicochem <- paste0("The following are predictions for ", chemical_name, " using physicochemical QSAR models available in Opera. These models generate output in a variety of formats. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_opera_physicochem2 <- apply(opera_physicochem, 1, function(x){
    #     paste0(x["model_name"], " - ", x["model_description"], ": ", x["model_value"])
    # })
    # text_opera_physicochem <- paste0(text_opera_physicochem, "\n\n", paste0(text_opera_physicochem2, collapse="\n"))
    # writeLines(text_opera_physicochem, paste0("./reports/opera_physicochem__", dtxsids, ".txt"))
    # 
    # text_opera_structural_properties <- paste0("The following are predictions for ", chemical_name, " using structural property QSAR models available in Opera. These models generate output in a variety of formats. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_opera_structural_properties2 <- apply(opera_structural_properties, 1, function(x){
    #     paste0(x["model_name"], " - ", x["model_description"], ": ", x["model_value"])
    # })
    # text_opera_structural_properties <- paste0(text_opera_structural_properties, "\n\n", paste0(text_opera_structural_properties2, collapse="\n"))
    # writeLines(text_opera_structural_properties, paste0("./reports/opera_structural_properties__", dtxsids, ".txt"))
    # 
    # text_opera_toxicology_endpoints <- paste0("The following are predictions for ", chemical_name, " using toxicology endpoint QSAR models available in Opera. These models generate output in a variety of formats. Each entry in the list is given as: [model name] - [description]: [value]. Note that these results are purely predictive and may not accurately reflect the behavior of the chemical in the real world. This report was automatically generated by ChemBioTox.")
    # text_opera_toxicology_endpoints2 <- apply(opera_toxicology_endpoints, 1, function(x){
    #     paste0(x["model_name"], " - ", x["model_description"], ": ", x["model_value"])
    # })
    # text_opera_toxicology_endpoints <- paste0(text_opera_toxicology_endpoints, "\n\n", paste0(text_opera_toxicology_endpoints2, collapse="\n"))
    # writeLines(text_opera_toxicology_endpoints, paste0("./reports/opera_toxicology_endpoints__", dtxsids, ".txt"))
    # 
    # ### SAAGAR ###
    # text_saagar <- paste0("The following are structural alerts for ", chemical_name, " according to Saagar. This report was automatically generated by ChemBioTox.")
    # text_saagar2 <- apply(saagar, 1, function(x){
    #     paste0(chemical_name, " has the alert: ", x["alert_name"], ".")
    # })
    # text_saagar <- paste0(text_saagar, "\n\n", paste0(text_saagar2, collapse="\n"))
    # writeLines(text_saagar, paste0("./reports/saagar__", dtxsids, ".txt"))
    # 
    # ### T3DB ###
    # text_t3db <- paste0("The following are targets for ", chemical_name, " according to the Toxin and Toxin Targets Database (T3DB). This report was automatically generated by ChemBioTox.")
    # text_t3db2 <- apply(t3db, 1, function(x){
    #     paste0(chemical_name, " has the target: ", x["target_name"], ".")
    # })
    # text_t3db <- paste0(text_t3db, "\n\n", paste0(text_t3db2, collapse="\n"))
    # writeLines(text_t3db, paste0("./reports/t3db__", dtxsids, ".txt"))
    # 
    # 
    # ### TOXREFDB ###
    # text_toxrefdb_neoplastic <- paste0("The following are neoplastic annotations for ", chemical_name, " according to ToxRefDB. This report was automatically generated by ChemBioTox.")
    # text_toxrefdb_neoplastic2 <- apply(toxrefdb_neoplastic, 1, function(x){
    #     paste0(chemical_name, " has the annotation: ", x["annotation"], ".")
    # })
    # text_toxrefdb_neoplastic <- paste0(text_toxrefdb_neoplastic, "\n\n", paste0(text_toxrefdb_neoplastic2, collapse="\n"))
    # writeLines(text_toxrefdb_neoplastic, paste0("./reports/toxrefdb_neoplastic__", dtxsids, ".txt"))
    # 
    # text_toxrefdb_nonneoplastic <- paste0("The following are non-neoplastic annotations for ", chemical_name, " according to ToxRefDB. This report was automatically generated by ChemBioTox.")
    # text_toxrefdb_nonneoplastic2 <- apply(toxrefdb_nonneoplastic, 1, function(x){
    #     paste0(chemical_name, " has the annotation: ", x["annotation"], ".")
    # })
    # text_toxrefdb_nonneoplastic <- paste0(text_toxrefdb_nonneoplastic, "\n\n", paste0(text_toxrefdb_nonneoplastic2, collapse="\n"))
    # writeLines(text_toxrefdb_nonneoplastic, paste0("./reports/toxrefdb_nonneoplastic__", dtxsids, ".txt"))
    # 
    # ### GRAS ###
    # text_gras <- paste0("The following are SCOGS conclusions on the safety of ", chemical_name, " from the Generally Recognized As Safe (GRAS) database. This report was automatically generated by ChemBioTox.")
    # text_gras2 <- apply(gras, 1, function(x){
    #     subbed <- gsub("[substance]", chemical_name, x["scogs_interpretation"], fixed=TRUE)
    #     paste0(subbed, " (SCOGS report number: ", x["scogs_report_number"], ")")
    # })
    # text_gras <- paste0(text_gras, "\n\n", paste0(text_gras2, collapse="\n"))
    # writeLines(text_gras, paste0("./reports/gras__", dtxsids, ".txt"))
    # 
    # ### PUBCHEM ###
    # text_pubchem_bioassays <- paste0("The following are bioassays for ", chemical_name, " from PubChem. This report was automatically generated by ChemBioTox.")
    # text_pubchem_bioassays2 <- apply(pubchem_bioassays, 1, function(x){
    #     paste0("According to the assay with AID: ", x["aid"], ", ", chemical_name, " has ", x["activity_name"], " = ", x["activity_value"], " (outcome: ", x["activity_outcome"], ") for the protein(s): ", x["protein_accessions"], ", (source: ", x["source_name"], ")")
    # })
    # text_pubchem_bioassays <- paste0(text_pubchem_bioassays, "\n\n", paste0(text_pubchem_bioassays2, collapse="\n"))
    # writeLines(text_pubchem_bioassays, paste0("./reports/bioassays__", dtxsids, ".txt"))
    # 
    # 
    # ### FOODB ###
    # text_foodb_enzymes <- paste0("The following are enzymes associated with ", chemical_name, " according to the FooDB. This report was automatically generated by ChemBioTox.")
    # text_foodb_enzymes2 <- apply(foodb_enzymes, 1, function(x){
    #     paste0(chemical_name, " is associated with the enzyme: ", x["enzyme_name"], " (source: ", x["citations"], ")")
    # })
    # text_foodb_enzymes <- paste0(text_foodb_enzymes, "\n\n", paste0(text_foodb_enzymes2, collapse="\n"))
    # writeLines(text_foodb_enzymes, paste0("./reports/foodb_enzymes__", dtxsids, ".txt"))
    # 
    # 
    # text_foodb_flavors <- paste0("The following are flavors associated with ", chemical_name, " according to the FooDB. This report was automatically generated by ChemBioTox.")
    # text_foodb_flavors2 <- apply(foodb_flavors, 1, function(x){
    #     paste0(chemical_name, " has the flavor: ", x["flavor_name"], " (source: ", x["citations"], ")")
    # })
    # text_foodb_flavors <- paste0(text_foodb_flavors, "\n\n", paste0(text_foodb_flavors2, collapse="\n"))
    # writeLines(text_foodb_flavors, paste0("./reports/foodb_flavors__", dtxsids, ".txt"))
    # 
    # 
    # text_foodb_foodcontent <- paste0(chemical_name, " may be found in the following foods, according to the FooDB. This report was automatically generated by ChemBioTox.")
    # text_foodb_foodcontent2 <- apply(foodb_foodcontent, 1, function(x){
    #     paste0(chemical_name, " is found in : ", x["food_subgroup"], ", which is in the group of ", x["food_group"])
    # })
    # text_foodb_foodcontent <- paste0(text_foodb_foodcontent, "\n\n", paste0(text_foodb_foodcontent2, collapse="\n"))
    # writeLines(text_foodb_foodcontent, paste0("./reports/foodb_foodcontent__", dtxsids, ".txt"))
    # 
    # 
    # text_foodb_healtheffects <- paste0(chemical_name, " may have the following health effects, according to the FooDB. This report was automatically generated by ChemBioTox.")
    # text_foodb_healtheffects2 <- apply(foodb_healtheffects, 1, function(x){
    #     paste0(chemical_name, " functions as a(n): ", x["health_effect_name"])
    # })
    # text_foodb_healtheffects <- paste0(text_foodb_healtheffects, "\n\n", paste0(text_foodb_healtheffects2, collapse="\n"))
    # writeLines(text_foodb_healtheffects, paste0("./reports/foodb_healtheffects__", dtxsids, ".txt"))
    # 
    # 
    # text_foodb_ontology <- paste0(chemical_name, " has the following ontological relationships, according to the FooDB. This report was automatically generated by ChemBioTox.")
    # text_foodb_ontology2 <- apply(foodb_ontology, 1, function(x){
    #     paste0(chemical_name, " has an ontological relationship with: ", x["term"])
    # })
    # text_foodb_ontology <- paste0(text_foodb_ontology, "\n\n", paste0(text_foodb_ontology2, collapse="\n"))
    # writeLines(text_foodb_ontology, paste0("./reports/foodb_ontology__", dtxsids, ".txt"))
    
    
    ### EPA ###
    # text_epa_props <- paste0("The following are chemical properties of ", chemical_name, " according to the Environmental Protection Agency (EPA). This report was automatically generated by ChemBioTox.")
    # text_epa_props2 <- apply(epa_props, 1, function(x){
    #     if(x["epa_attribute"] == "48HR_DAPHNIA_LC50_MOL/L_TEST_PRED"){
    #         return(paste0(chemical_name, " was predicted to have a lethal concentration of ", x["epa_attribute_value"], " mol/L in 50% of test Daphnia (LC50) after 48 hours according to TEST predictive models"))
    #     } else if(x["epa_attribute"] == "96HR_FATHEAD_MINNOW_MOL/L_TEST_PRED"){
    #         return(paste0(chemical_name, " xxx: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "AMES_MUTAGENICITY_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted AMES mutagenicity of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "ATMOSPHERIC_HYDROXYLATION_RATE_(AOH)_CM3/MOLECULE*SEC_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted atmospheric hydroxylation rate (AOH) of: ", x["epa_attribute_value"], " cm^3/molecule*sec according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "AVERAGE_MASS"){
    #         return(paste0(chemical_name, " has an average mass of: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "BIOCONCENTRATION_FACTOR_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted bioconcentration factor of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "BIOCONCENTRATION_FACTOR_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted bioconcentration factor of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "BIODEGRADATION_HALF_LIFE_DAYS_DAYS_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted biodegration half life of: ", x["epa_attribute_value"], " days according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "BOILING_POINT_DEGC_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted boiling point of: ", x["epa_attribute_value"], " degrees celsius according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "BOILING_POINT_DEGC_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted boiling point of: ", x["epa_attribute_value"], " degrees celsius according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "CPDAT_COUNT"){
    #         return(paste0(chemical_name, " xxx: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "DATA_SOURCES"){
    #         return(paste0(chemical_name, " has the following sources: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "DENSITY_G/CM^3_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted density (g/cm^3) of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "DEVTOX_TEST_PRED"){
    #         return(paste0(chemical_name, " has the following predicted developmental toxicity (devtox) data: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "EXPOCAST"){
    #         return(paste0(chemical_name, " has the following Expocast data: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "EXPOCAST_MEDIAN_EXPOSURE_PREDICTION_MG/KG-BW/DAY"){
    #         return(paste0(chemical_name, " has a predicted median exposure (mg/kg-bw/day) of: ", x["epa_attribute_value"], " according to Expocast"))
    #     } else if(x["epa_attribute"] == "FLASH_POINT_DEGC_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted flash point (celsius) of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "HENRYS_LAW_ATM-M3/MOLE_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted Henry's Law constant (atm-m3/mole) of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "IRIS_LINK"){
    #         return(paste0(chemical_name, " has an integrated risk information system (IRIS) report: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "LOGD5.5"){
    #         return(paste0(chemical_name, " has a LogD value in pH 5.5 of: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "LOGD7.4"){
    #         return(paste0(chemical_name, " has a LogD value in pH 7.4 of: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "MELTING_POINT_DEGC_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted melting point (celsius) of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "MELTING_POINT_DEGC_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted melting point (celsius) of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "MOLECULAR_FORMULA"){
    #         return(paste0(chemical_name, " has a molecular formula of: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "MONOISOTOPIC_MASS"){
    #         return(paste0(chemical_name, " has a monoisotopic mass of: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "NHANES"){
    #         return(paste0(chemical_name, " has predicted exposure data from NHANES: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "NUMBER_OF_PUBMED_ARTICLES"){
    #         return(paste0("There are ", x["epa_attribute_value"], " PubMed articles related to ", chemical_name))
    #     } else if(x["epa_attribute"] == "OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted air partition coefficient (logKoa) of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted water partition coefficient (logP) of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "OPERA_KM_DAYS_OPERA_PRED"){
    #         return(paste0(chemical_name, " xxx: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "OPERA_PKAA_OPERA_PRED"){
    #         return(paste0(chemical_name, " xxx: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "OPERA_PKAB_OPERA_PRED"){
    #         return(paste0(chemical_name, " xxx: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "ORAL_RAT_LD50_MOL/KG_TEST_PRED"){
    #         return(paste0(chemical_name, " was predicted to have a lethal dose of ", x["epa_attribute_value"], " mol/kg in 50% of test rats (LD50) when administered orally according to TEST predictive models"))
    #     } else if(x["epa_attribute"] == "PPRTV_LINK"){
    #         return(paste0(chemical_name, " has the following EPA Provisional Peer Reviewed Toxicity Values (PPRTV) for Superfund reports: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "PUBCHEM_DATA_SOURCES"){
    #         return(paste0(chemical_name, " has the following PubChem data sources: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "QC_LEVEL"){
    #         return(paste0(chemical_name, " has the QC level: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "QC_NOTES"){
    #         return(paste0(chemical_name, " has the additional QC notes: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "READY_BIO_DEG"){
    #         return(paste0(chemical_name, " xxx: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "SAFETY_DATA"){
    #         return(paste0(chemical_name, " has the following safety data: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "SOIL_ADSORPTION_COEFFICIENT_KOC_L/KG_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted soil adsorption coefficient of: ", x["epa_attribute_value"], " L/kg according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "SURFACE_TENSION_DYN/CM_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted surface tension of: ", x["epa_attribute_value"], " dyn/cm according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "TETRAHYMENA_PYRIFORMIS_IGC50_MOL/L_TEST_PRED"){
    #         return(paste0(chemical_name, " is predicted to inhibit 50% of growth in Tetrahymena pyriformis at a concentration of: ", x["epa_attribute_value"], " mol/L according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "THERMAL_CONDUCTIVITY_MW/(M*K)_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted thermal conductivity of: ", x["epa_attribute_value"], " mW/(m*k) according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "TOXCAST_NUMBER_OF_ASSAYS/TOTAL"){
    #         return(paste0(chemical_name, " has ", x["epa_attribute_value"], " assays in ToxCast"))
    #     } else if(x["epa_attribute"] == "TOXCAST_PERCENT_ACTIVE"){
    #         return(paste0(chemical_name, " has : ", x["epa_attribute_value"], " percent actives according to ToxCast"))
    #     } else if(x["epa_attribute"] == "TOXVAL_DATA"){
    #         return(paste0(chemical_name, " has the following toxicity data from ToxVal: ", x["epa_attribute_value"]))
    #     } else if(x["epa_attribute"] == "VAPOR_PRESSURE_MMHG_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted vapor pressure (mmHg) of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "VAPOR_PRESSURE_MMHG_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted vapor pressure (mmHg) of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "VISCOSITY_CP_CP_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted viscosity of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "WATER_SOLUBILITY_MOL/L_OPERA_PRED"){
    #         return(paste0(chemical_name, " has a predicted water solubility (mol/L) of: ", x["epa_attribute_value"], " according to OPERA model predictions"))
    #     } else if(x["epa_attribute"] == "WATER_SOLUBILITY_MOL/L_TEST_PRED"){
    #         return(paste0(chemical_name, " has a predicted water solubility (mol/L) of: ", x["epa_attribute_value"], " according to TEST model predictions"))
    #     } else if(x["epa_attribute"] == "WIKIPEDIA_ARTICLE"){
    #         return(paste0("Wikipedia article for ", chemical_name, ": ", x["epa_attribute_value"]))
    #     } else {
    #         return("")
    #     }
    # })
    # text_epa_props <- paste0(text_epa_props, "\n\n", paste0(text_epa_props2, collapse="\n"))
    # writeLines(text_epa_props, paste0("./reports/epa_props__", dtxsids, ".txt"))
    # 
    # 
    # text_pubchem_props <- paste0("The following are properties for ", chemical_name, " from PubChem. This report was automatically generated by ChemBioTox.")
    # text_pubchem_props2 <- apply(pubchem_props, 1, function(x){
    #     if(x["pubchem_attribute"] == "aids"){
    #         return(paste0(chemical_name, " has the following PubChem assay IDs: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "annotation"){
    #         return(paste0(chemical_name, " has the following PubChem annotations: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "canonicalsmiles"){
    #         return(paste0(chemical_name, " has the canonical SMILES: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "charge"){
    #         return(paste0(chemical_name, " has the charge: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "cmpdname"){
    #         return(paste0(chemical_name, " primarily goes by the name: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "cmpdsynonym"){
    #         return(paste0(chemical_name, " also goes by the name(s): ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "complexity"){
    #         return(paste0(chemical_name, " has a complexity of: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "covalentunitcnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " covalent units."))
    #     } else if(x["pubchem_attribute"] == "definedatomstereocnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " defined atom stereocenters."))
    #     } else if(x["pubchem_attribute"] == "definedbondstereocnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " defined bond stereocenters."))
    #     } else if(x["pubchem_attribute"] == "depcatg"){
    #         return(paste0(chemical_name, " is available from the following vendors: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "dsstox_substance_id"){
    #         return(paste0(chemical_name, " is identified by the DSSTox Substance ID (DTXSID): DTXSID", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "exactmass"){
    #         return(paste0(chemical_name, " has a mass of ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "gpfamilycnt"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "gpidcnt"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "hbondacc"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "hbonddonor"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "heavycnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " heavy atoms."))
    #     } else if(x["pubchem_attribute"] == "inchi"){
    #         return(paste0(chemical_name, " is identified by the InChI: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "inchikey"){
    #         return(paste0(chemical_name, " is identified by the InChIKey: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "isosmiles"){
    #         return(paste0(chemical_name, " is identified by the isometric SMILES: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "isotopeatomcnt"){
    #         return(paste0(chemical_name, " has: ", x["pubchem_value"], " isotope atoms."))
    #     } else if(x["pubchem_attribute"] == "iupacname"){
    #         return(paste0(chemical_name, " is identified by the IUPAC name: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "meshheadings"){
    #         return(paste0(chemical_name, " has the following MeSH classifications: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "mf"){
    #         return(paste0(chemical_name, " is represented by the molecular formula: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "monoisotopeicmass"){
    #         return(paste0(chemical_name, " has a monoisotopic mass of: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "mw"){
    #         return(paste0(chemical_name, " has a molecular weight of: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "neighbortype"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "pclidcnt"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "polararea"){
    #         return(paste0(chemical_name, " has a polar area: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "rotbonds"){
    #         return(paste0(chemical_name, " has: ", x["pubchem_value"], " rotatable bonds."))
    #     } else if(x["pubchem_attribute"] == "sid"){
    #         return(paste0(chemical_name, " is identified by the PubChem substance ID: ", x["pubchem_value"]))
    #     } else if(x["pubchem_attribute"] == "sidsrcname"){
    #         return(paste0(""))
    #     } else if(x["pubchem_attribute"] == "totalatomstereocnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " total (defined + undefined) atom stereocenters."))
    #     } else if(x["pubchem_attribute"] == "totalbondstereocnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " total (defined + undefined) bond stereocenters."))
    #     } else if(x["pubchem_attribute"] == "undefinedatomstereocnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " undefined atom stereocenters."))
    #     } else if(x["pubchem_attribute"] == "undefinedbondstereocnt"){
    #         return(paste0(chemical_name, " has ", x["pubchem_value"], " undefined bond stereocenters."))
    #     } else if(x["pubchem_attribute"] == "xlogp"){
    #         return(paste0(chemical_name, " has a partition coefficient (XLogP3) of: ", x["pubchem_value"]))
    #     } else {
    #         return(paste0(""))
    #     }
    # })
    # text_pubchem_props <- paste0(text_pubchem_props, "\n\n", paste0(text_pubchem_props2, collapse="\n"))
    # writeLines(text_pubchem_props, paste0("./reports/pubchem_props__", dtxsids, ".txt"))

}
    

generate_cluster_report <- function(clust_l3, cluster_scores, selected_node, report_images, report_annotations){
    topn_admet_binr <- NULL
    topn_chembl <- NULL
    topn_cpd <- NULL
    topn_ctd_bioprocess <- NULL
    topn_ctd_cellcomp <- NULL
    topn_ctd_diseases <- NULL
    topn_ctd_genes <- NULL
    topn_ctd_molfunct <- NULL
    topn_ctd_phenotypes <- NULL
    topn_drugbank_atccodes <- NULL
    topn_drugbank_carriers <- NULL
    topn_drugbank_enzymes <- NULL
    topn_drugbank_targets <- NULL
    topn_drugbank_transporters <- NULL
    topn_hmdb_biospecimenlocations <- NULL
    topn_hmdb_cellularlocations <- NULL
    topn_hmdb_diseases <- NULL
    topn_hmdb_genes <- NULL
    topn_hmdb_tissuelocations <- NULL
    topn_ice <- NULL
    topn_invitrodb <- NULL
    topn_leadscope <- NULL
    topn_ochem <- NULL
    topn_opera_adme <- NULL
    topn_opera_environmental_fate <- NULL
    topn_opera_physicochem <- NULL
    topn_opera_structural_properties <- NULL
    topn_opera_toxicology_endpoints <- NULL
    topn_saagar <- NULL
    topn_t3db <- NULL
    topn_toxrefdb_neoplastic <- NULL
    topn_toxrefdb_nonneoplastic <- NULL
    topn_pubchem <- NULL
    topn_pubchem_props <- NULL
    topn_gras <- NULL
    topn_foodb_enzymes <- NULL
    topn_foodb_flavors <- NULL
    topn_foodb_foodcontent <- NULL
    topn_foodb_healtheffects <- NULL
    topn_foodb_ontology <- NULL
    topn_epa_props <- NULL
    
    withProgress(message=paste0("Generating report for ", clust_l3, ": "), value=0, {
        setProgress(0.2, detail="Getting cluster info")
        
        out_cluster_info <- cluster_scores[, c("model_name", "clust_l3", "id_count", "id_mean", "id_std", "category", "subcategory", "endpoint_desc", "algorithm_desc", "id_mean_high", "id_mean_low", "info_score", "avg_score")]
        colnames(out_cluster_info) <- c("Model Name", "Cluster ID", "In-Domain Chemicals", "In-Domain Mean", "In-Domain Stddev.", "Annotation Category", "Annotation Subcategory", "Endpoint Description", "Algorithm Description", "In-Domain Mean (High)", "In-Domain Mean (Low)", "Info Score", "Mean Info Score (All Models)")
        
        # Get cluster model profile and statistics
        if("avg_profile_score" %in% colnames(cluster_scores)){
            out_cluster_info <- cluster_scores[, c("model_name", "clust_l3", "id_count", "id_mean", "id_std", "category", "subcategory", "endpoint_desc", "algorithm_desc", "id_mean_high", "id_mean_low", "info_score", "avg_score", "avg_profile_score")]
            colnames(out_cluster_info) <- c("Model Name", "Cluster ID", "In-Domain Chemicals", "In-Domain Mean", "In-Domain Stddev.", "Annotation Category", "Annotation Subcategory", "Endpoint Description", "Algorithm Description", "In-Domain Mean (High)", "In-Domain Mean (Low)", "Info Score", "Mean Info Score (All Models)", "Mean Info Score (Profile Models)")
        }
        
        setProgress(0.3, detail="Getting list of chemicals in cluster")
        
        # Get list of chemicals in cluster
        out_chemicals <- selected_node[, c("dsstox_substance_id", "preferred_name", "casrn", "qsar_ready_smiles", "original_smiles_string", "clust_l3", "class_tag", "centrality", "total_count", "seem3u95", "url")]
        
        struc_images <- list()
        if(report_images == TRUE){
            tmpdir <-tempdir()
            struc_images <- apply(selected_node, 1, function(x){
                img <- charToRaw(paste0(x["qsar_cleaned_image"]))
                name <- x["dsstox_substance_id"]
                rsvg_png(img, paste0(tmpdir, "/chemimg_", name, "_out.png"))
                paste0(tmpdir, "/chemimg_", name, "_out.png")
            })
            names(struc_images) <- selected_node$dsstox_substance_id
        }
        
        # Clean URL
        out_chemicals$url <- paste0("https://comptox.epa.gov/dashboard/chemical/details/", out_chemicals$dsstox_substance_id)
        colnames(out_chemicals) <- c("DTXSID", "Chemical Name", "CASRN", "Cleaned SMILES", "Original SMILES", "Cluster ID", "Class Tag", "Centrality", "Total Count", "SEEM3u95", "URL")
        
        if(report_annotations == TRUE){
            setProgress(0.5, detail="Getting annotations for chemicals in cluster")
            # Get annotations
            input_all_annotations <- list(
                "switch__admet_binr_chem"=TRUE,
                "switch__chembl_chem"=TRUE,
                "switch__cpd_chem"=TRUE,
                "switch__ctd_bioprocess_chem"=TRUE,
                "switch__ctd_cellcomp_chem"=TRUE,
                "switch__ctd_diseases_chem"=TRUE,
                "switch__ctd_genes_chem"=TRUE,
                "switch__ctd_molfunct_chem"=TRUE,
                "switch__ctd_phenotypes_chem"=TRUE,
                "switch__drugbank_atccodes_chem"=TRUE,
                "switch__drugbank_carriers_chem"=TRUE,
                "switch__drugbank_enzymes_chem"=TRUE,
                "switch__drugbank_targets_chem"=TRUE,
                "switch__drugbank_transporters_chem"=TRUE,
                "switch__hmdb_biospecimenlocations_chem"=TRUE,
                "switch__hmdb_cellularlocations_chem"=TRUE,
                "switch__hmdb_diseases_chem"=TRUE,
                "switch__hmdb_genes_chem"=TRUE,
                "switch__hmdb_tissuelocations_chem"=TRUE,
                "switch__ice_chem"=TRUE,
                "switch__invitrodb_chem"=TRUE,
                "switch__leadscope_chem"=TRUE,
                "switch__ochem_chem"=TRUE,
                "switch__opera_adme_chem"=TRUE,
                "switch__opera_environmental_fate_chem"=TRUE,
                "switch__opera_physicochem_chem"=TRUE,
                "switch__opera_structural_properties_chem"=TRUE,
                "switch__opera_toxicology_endpoints_chem"=TRUE,
                "switch__saagar_chem"=TRUE,
                "switch__t3db_chem"=TRUE,
                "switch__toxrefdb_neoplastic_chem"=TRUE,
                "switch__toxrefdb_nonneoplastic_chem"=TRUE,
                "switch__pubchem_chem"=TRUE,
                "switch__pubchem_props_chem"=TRUE,
                "switch__gras_chem"=TRUE,
                "switch__foodb_enzymes_chem"=TRUE,
                "switch__foodb_flavors_chem"=TRUE,
                "switch__foodb_foodcontent_chem"=TRUE,
                "switch__foodb_healtheffects_chem"=TRUE,
                "switch__foodb_ontology_chem"=TRUE,
                "switch__epa_props_chem"=TRUE
            )
            
            setProgress(0.7, detail="Processing annotations for chemicals in cluster")
            
            tmp <- chemical_annotations(selected=as.integer(selected_node$epa_id), input=input_all_annotations, selected_node=clust_l3, dtxsids=selected_node$dsstox_substance_id, switch_mode="_chem")
            
            topn_admet_binr <- tmp[["anno_admet_binr"]]
            topn_chembl <- tmp[["anno_chembl"]]
            topn_cpd <- tmp[["anno_cpd"]]
            topn_ctd_bioprocess <- tmp[["anno_ctd_bioprocess"]]
            topn_ctd_cellcomp <- tmp[["anno_ctd_cellcomp"]]
            topn_ctd_diseases <- tmp[["anno_ctd_diseases"]]
            topn_ctd_genes <- tmp[["anno_ctd_genes"]]
            topn_ctd_molfunct <- tmp[["anno_ctd_molfunct"]]
            topn_ctd_phenotypes <- tmp[["anno_ctd_phenotypes"]]
            topn_drugbank_atccodes <- tmp[["anno_drugbank_atccodes"]]
            topn_drugbank_carriers <- tmp[["anno_drugbank_carriers"]]
            topn_drugbank_enzymes <- tmp[["anno_drugbank_enzymes"]]
            topn_drugbank_targets <- tmp[["anno_drugbank_targets"]]
            topn_drugbank_transporters <- tmp[["anno_drugbank_transporters"]]
            topn_hmdb_biospecimenlocations <- tmp[["anno_hmdb_biospecimenlocations"]]
            topn_hmdb_cellularlocations <- tmp[["anno_hmdb_cellularlocations"]]
            topn_hmdb_diseases <- tmp[["anno_hmdb_diseases"]]
            topn_hmdb_genes <- tmp[["anno_hmdb_genes"]]
            topn_hmdb_tissuelocations <- tmp[["anno_hmdb_tissuelocations"]]
            topn_ice <- tmp[["anno_ice"]]
            topn_invitrodb <- tmp[["anno_invitrodb"]]
            topn_leadscope <- tmp[["anno_leadscope"]]
            topn_ochem <- tmp[["anno_ochem"]]
            topn_opera_adme <- tmp[["anno_opera_adme"]]
            topn_opera_environmental_fate <- tmp[["anno_opera_environmental_fate"]]
            topn_opera_physicochem <- tmp[["anno_opera_physicochem"]]
            topn_opera_structural_properties <- tmp[["anno_opera_structural_properties"]]
            topn_opera_toxicology_endpoints <- tmp[["anno_opera_toxicology_endpoints"]]
            topn_saagar <- tmp[["anno_saagar"]]
            topn_t3db <- tmp[["anno_t3db"]]
            topn_toxrefdb_neoplastic <- tmp[["anno_toxrefdb_neoplastic"]]
            topn_toxrefdb_nonneoplastic <- tmp[["anno_toxrefdb_nonneoplastic"]]
            topn_pubchem <- tmp[["anno_pubchem"]]
            topn_pubchem_props <- tmp[["anno_pubchem_props"]]
            topn_gras <- tmp[["anno_gras"]]
            topn_foodb_enzymes <- tmp[["anno_foodb_enzymes"]]
            topn_foodb_flavors <- tmp[["anno_foodb_flavors"]]
            topn_foodb_foodcontent <- tmp[["anno_foodb_foodcontent"]]
            topn_foodb_healtheffects <- tmp[["anno_foodb_healtheffects"]]
            topn_foodb_ontology <- tmp[["anno_foodb_ontology"]]
            topn_epa_props <- tmp[["anno_epa_props"]]
        }
        
        setProgress(0.9, detail="Writing data to spreadsheet")
        
        wb <- createWorkbook(paste0("Cluster: ", clust_l3))
        data_to_write <- list(
            "Cluster Information"=out_cluster_info,
            "Chemical List"=out_chemicals
        )
        if(report_annotations == TRUE){
            data_to_write <- list(
                "Cluster Information"=out_cluster_info,
                "Chemical List"=out_chemicals,
                "ADMET Binary Models"=topn_admet_binr,
                "ChEMBL Struc. Alerts"=topn_chembl,
                "Leadscope Models"=topn_leadscope,
                "OChem Struc. Alerts"=topn_ochem,
                "Opera ADME Models"=topn_opera_adme,
                "Opera Env. Fate Models"=topn_opera_environmental_fate,
                "Opera Physicochem. Models"=topn_opera_physicochem,
                "Opera Struc. Properties"=topn_opera_structural_properties,
                "Opera Tox. Endpoints"=topn_opera_toxicology_endpoints,
                "Saagar Descriptors"=topn_saagar,
                "CTD Bioprocess"=topn_ctd_bioprocess,
                "CTD Cellcomp."=topn_ctd_cellcomp,
                "CTD Diseases"=topn_ctd_diseases,
                "CTD Genes"=topn_ctd_genes,
                "CTD Molfunc."=topn_ctd_molfunct,
                "CTD Phenotypes"=topn_ctd_phenotypes,
                "ICE Assays"=topn_ice,
                "T3DB Targets"=topn_t3db,
                "ToxRefDB Neoplastic"=topn_toxrefdb_neoplastic,
                "ToxRefDB Non-neoplastic"=topn_toxrefdb_nonneoplastic,
                "HMDB Biospecimen Loc."=topn_hmdb_biospecimenlocations,
                "HMDB Cellular Loc."=topn_hmdb_cellularlocations,
                "HMDB Diseases"=topn_hmdb_diseases,
                "HMDB Genes"=topn_hmdb_genes,
                "HMDB Tissue Loc."=topn_hmdb_tissuelocations,
                "CPD Products"=topn_cpd,
                "DrugBank ATC Codes"=topn_drugbank_atccodes,
                "DrugBank Carriers"=topn_drugbank_carriers,
                "DrugBank Enzymes"=topn_drugbank_enzymes,
                "DrugBank Targets"=topn_drugbank_targets,
                "DrugBank Transporters"=topn_drugbank_transporters,
                "InVitroDB Assays"=topn_invitrodb,
                "PubChem Bioassays"=topn_pubchem,
                "PubChem Phys. Props."=topn_pubchem_props,
                "GRAS Safety Recog. Studies"=topn_gras,
                "FooDB Enzymes"=topn_foodb_enzymes,
                "FooDB Flavors"=topn_foodb_flavors,
                "FooDB Food Content"=topn_foodb_foodcontent,
                "FooDB Health Effects"=topn_foodb_healtheffects,
                "FooDB Ontology"=topn_foodb_ontology,
                "EPA Phys. Props."=topn_epa_props
            )
        }
        
        for(sheet in names(data_to_write)){
            addWorksheet(wb, sheet)
            if(nrow(data_to_write[[sheet]]) > 0){
                writeDataTable(wb, sheet, x=data_to_write[[sheet]], startCol=1, startRow=1)
                # Special per sheet formatting
                if(sheet == "Cluster Information"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 6, 7, 8),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "Chemical List"){
                    img_i <- 2
                    for(struc_img in struc_images){
                        insertImage(wb, sheet, file=struc_img, startRow=img_i, startCol=12, width=1, height=1)
                        img_i <- img_i + 1
                    }
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 2, 4, 5, 11, 12),
                        widths=c(20, 100, 100, 100, 100, 20)
                    )
                    if(report_images == TRUE){
                        setRowHeights(
                            wb,
                            sheet,
                            rows=seq(2, nrow(data_to_write[[sheet]])),
                            heights=unlist(lapply(seq(2, nrow(data_to_write[[sheet]])), function(x) 100))
                        )
                    }
                } else if(sheet == "ADMET Binary Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6),
                        widths=c(20, 20, 20, 200)
                    )
                } else if(sheet == "Leadscope Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6),
                        widths=c(20, 20, 20, 100)
                    )
                } else if(sheet == "OChem Struc. Alerts"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "Opera ADME Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 100)
                    )
                } else if(sheet == "Opera Env. Fate Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 200)
                    )
                } else if(sheet == "Opera Physicochem. Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 200)
                    )
                } else if(sheet == "Opera Struc. Properties"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 100)
                    )
                } else if(sheet == "Opera Tox. Endpoints"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 200)
                    )
                } else if(sheet == "Saagar Descriptors"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "Saagar Descriptors"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Bioprocess"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Cellcomp."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Diseases"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5, 6),
                        widths=c(20, 20, 20, 20, 20)
                    )
                } else if(sheet == "CTD Genes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 7, 8, 9),
                        widths=c(20, 20, 20, 20, 20, 20)
                    )
                } else if(sheet == "CTD Molfunc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Phenotypes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7, 8, 9, 10),
                        widths=c(20, 20, 20, 20, 20, 20, 20, 20)
                    )
                } else if(sheet == "ICE Assays"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 4, 5, 21, 22),
                        widths=c(20, 20, 20, 20, 20)
                    )
                } else if(sheet == "T3DB Targets"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "ToxRefDB Neoplastic"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "ToxRefDB Non-neoplastic"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Biospecimen Loc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Cellular Loc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Diseases"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Genes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Tissue Loc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CPD Products"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank ATC Codes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "DrugBank Carriers"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank Enzymes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank Targets"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank Transporters"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "InVitroDB Assays"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "PubChem Bioassays"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "PubChem Phys. Props."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "GRAS Safety Recog. Studies"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Enzymes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Flavors"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Food Content"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Health Effects"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Ontology"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "EPA Phys. Props."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                }
            }
        }
        return(wb)
    })
}


generate_chemical_report <- function(cluster_scores, selected_node, report_images, report_annotations){
    topn_admet_binr <- NULL
    topn_chembl <- NULL
    topn_cpd <- NULL
    topn_ctd_bioprocess <- NULL
    topn_ctd_cellcomp <- NULL
    topn_ctd_diseases <- NULL
    topn_ctd_genes <- NULL
    topn_ctd_molfunct <- NULL
    topn_ctd_phenotypes <- NULL
    topn_drugbank_atccodes <- NULL
    topn_drugbank_carriers <- NULL
    topn_drugbank_enzymes <- NULL
    topn_drugbank_targets <- NULL
    topn_drugbank_transporters <- NULL
    topn_hmdb_biospecimenlocations <- NULL
    topn_hmdb_cellularlocations <- NULL
    topn_hmdb_diseases <- NULL
    topn_hmdb_genes <- NULL
    topn_hmdb_tissuelocations <- NULL
    topn_ice <- NULL
    topn_invitrodb <- NULL
    topn_leadscope <- NULL
    topn_ochem <- NULL
    topn_opera_adme <- NULL
    topn_opera_environmental_fate <- NULL
    topn_opera_physicochem <- NULL
    topn_opera_structural_properties <- NULL
    topn_opera_toxicology_endpoints <- NULL
    topn_saagar <- NULL
    topn_t3db <- NULL
    topn_toxrefdb_neoplastic <- NULL
    topn_toxrefdb_nonneoplastic <- NULL
    topn_pubchem <- NULL
    topn_pubchem_props <- NULL
    topn_gras <- NULL
    topn_foodb_enzymes <- NULL
    topn_foodb_flavors <- NULL
    topn_foodb_foodcontent <- NULL
    topn_foodb_healtheffects <- NULL
    topn_foodb_ontology <- NULL
    topn_epa_props <- NULL
    
    withProgress(message=paste0("Generating report for submitted chemicals: "), value=0, {
        setProgress(0.3, detail="Getting chemical info")
        
        # Get list of chemicals in cluster
        out_chemicals <- selected_node[, c("dsstox_substance_id", "preferred_name", "casrn", "qsar_ready_smiles", "original_smiles_string", "url")]
        if("similarity" %in% colnames(selected_node)){
            out_chemicals <- selected_node[, c("dsstox_substance_id", "preferred_name", "casrn", "qsar_ready_smiles", "original_smiles_string", "similarity", "url")]
        }
        
        struc_images <- list()
        if(report_images == TRUE){
            tmpdir <-tempdir()
            struc_images <- apply(selected_node, 1, function(x){
                img_str <- paste0(x["qsar_cleaned_image"])
                if(nchar(img_str) < 1){
                    img_str <- "<svg>No image</svg>"
                }
                
                img <- charToRaw(img_str)
                name <- x["dsstox_substance_id"]
                rsvg_png(img, paste0(tmpdir, "/chemimg_", name, "_out.png"))
                paste0(tmpdir, "/chemimg_", name, "_out.png")
            })
            names(struc_images) <- selected_node$dsstox_substance_id
        }
        
        # Clean URL
        out_chemicals$url <- paste0("https://comptox.epa.gov/dashboard/chemical/details/", out_chemicals$dsstox_substance_id)
        if("similarity" %in% colnames(selected_node)){
            colnames(out_chemicals) <- c("DTXSID", "Chemical Name", "CASRN", "Cleaned SMILES", "Original SMILES", "Similarity", "URL")
        } else {
            colnames(out_chemicals) <- c("DTXSID", "Chemical Name", "CASRN", "Cleaned SMILES", "Original SMILES", "URL")
        }
        
        if(report_annotations == TRUE){
            setProgress(0.5, detail="Getting annotations for chemicals in cluster")
            # Get annotations
            input_all_annotations <- list(
                "switch__admet_binr_chem"=TRUE,
                "switch__chembl_chem"=TRUE,
                "switch__cpd_chem"=TRUE,
                "switch__ctd_bioprocess_chem"=TRUE,
                "switch__ctd_cellcomp_chem"=TRUE,
                "switch__ctd_diseases_chem"=TRUE,
                "switch__ctd_genes_chem"=TRUE,
                "switch__ctd_molfunct_chem"=TRUE,
                "switch__ctd_phenotypes_chem"=TRUE,
                "switch__drugbank_atccodes_chem"=TRUE,
                "switch__drugbank_carriers_chem"=TRUE,
                "switch__drugbank_enzymes_chem"=TRUE,
                "switch__drugbank_targets_chem"=TRUE,
                "switch__drugbank_transporters_chem"=TRUE,
                "switch__hmdb_biospecimenlocations_chem"=TRUE,
                "switch__hmdb_cellularlocations_chem"=TRUE,
                "switch__hmdb_diseases_chem"=TRUE,
                "switch__hmdb_genes_chem"=TRUE,
                "switch__hmdb_tissuelocations_chem"=TRUE,
                "switch__ice_chem"=TRUE,
                "switch__invitrodb_chem"=TRUE,
                "switch__leadscope_chem"=TRUE,
                "switch__ochem_chem"=TRUE,
                "switch__opera_adme_chem"=TRUE,
                "switch__opera_environmental_fate_chem"=TRUE,
                "switch__opera_physicochem_chem"=TRUE,
                "switch__opera_structural_properties_chem"=TRUE,
                "switch__opera_toxicology_endpoints_chem"=TRUE,
                "switch__saagar_chem"=TRUE,
                "switch__t3db_chem"=TRUE,
                "switch__toxrefdb_neoplastic_chem"=TRUE,
                "switch__toxrefdb_nonneoplastic_chem"=TRUE,
                "switch__pubchem_chem"=TRUE,
                "switch__pubchem_props_chem"=TRUE,
                "switch__gras_chem"=TRUE,
                "switch__foodb_enzymes_chem"=TRUE,
                "switch__foodb_flavors_chem"=TRUE,
                "switch__foodb_foodcontent_chem"=TRUE,
                "switch__foodb_healtheffects_chem"=TRUE,
                "switch__foodb_ontology_chem"=TRUE,
                "switch__epa_props_chem"=TRUE
            )
            
            setProgress(0.7, detail="Processing annotations for chemicals in cluster")
            
            print("here 1")
            
            tmp <- chemical_annotations(selected=as.integer(selected_node$epa_id), input=input_all_annotations, selected_node="submitted", dtxsids=selected_node$dsstox_substance_id, switch_mode="_chem")
            
            print("here 2")
            
            topn_admet_binr <- tmp[["anno_admet_binr"]]
            topn_chembl <- tmp[["anno_chembl"]]
            topn_cpd <- tmp[["anno_cpd"]]
            topn_ctd_bioprocess <- tmp[["anno_ctd_bioprocess"]]
            topn_ctd_cellcomp <- tmp[["anno_ctd_cellcomp"]]
            topn_ctd_diseases <- tmp[["anno_ctd_diseases"]]
            topn_ctd_genes <- tmp[["anno_ctd_genes"]]
            topn_ctd_molfunct <- tmp[["anno_ctd_molfunct"]]
            topn_ctd_phenotypes <- tmp[["anno_ctd_phenotypes"]]
            topn_drugbank_atccodes <- tmp[["anno_drugbank_atccodes"]]
            topn_drugbank_carriers <- tmp[["anno_drugbank_carriers"]]
            topn_drugbank_enzymes <- tmp[["anno_drugbank_enzymes"]]
            topn_drugbank_targets <- tmp[["anno_drugbank_targets"]]
            topn_drugbank_transporters <- tmp[["anno_drugbank_transporters"]]
            topn_hmdb_biospecimenlocations <- tmp[["anno_hmdb_biospecimenlocations"]]
            topn_hmdb_cellularlocations <- tmp[["anno_hmdb_cellularlocations"]]
            topn_hmdb_diseases <- tmp[["anno_hmdb_diseases"]]
            topn_hmdb_genes <- tmp[["anno_hmdb_genes"]]
            topn_hmdb_tissuelocations <- tmp[["anno_hmdb_tissuelocations"]]
            topn_ice <- tmp[["anno_ice"]]
            topn_invitrodb <- tmp[["anno_invitrodb"]]
            topn_leadscope <- tmp[["anno_leadscope"]]
            topn_ochem <- tmp[["anno_ochem"]]
            topn_opera_adme <- tmp[["anno_opera_adme"]]
            topn_opera_environmental_fate <- tmp[["anno_opera_environmental_fate"]]
            topn_opera_physicochem <- tmp[["anno_opera_physicochem"]]
            topn_opera_structural_properties <- tmp[["anno_opera_structural_properties"]]
            topn_opera_toxicology_endpoints <- tmp[["anno_opera_toxicology_endpoints"]]
            topn_saagar <- tmp[["anno_saagar"]]
            topn_t3db <- tmp[["anno_t3db"]]
            topn_toxrefdb_neoplastic <- tmp[["anno_toxrefdb_neoplastic"]]
            topn_toxrefdb_nonneoplastic <- tmp[["anno_toxrefdb_nonneoplastic"]]
            topn_pubchem <- tmp[["anno_pubchem"]]
            topn_pubchem_props <- tmp[["anno_pubchem_props"]]
            topn_gras <- tmp[["anno_gras"]]
            topn_foodb_enzymes <- tmp[["anno_foodb_enzymes"]]
            topn_foodb_flavors <- tmp[["anno_foodb_flavors"]]
            topn_foodb_foodcontent <- tmp[["anno_foodb_foodcontent"]]
            topn_foodb_healtheffects <- tmp[["anno_foodb_healtheffects"]]
            topn_foodb_ontology <- tmp[["anno_foodb_ontology"]]
            topn_epa_props <- tmp[["anno_epa_props"]]
        }
        
        setProgress(0.9, detail="Writing data to spreadsheet")
        
        wb <- createWorkbook(paste0("Submitted chemicals"))
        data_to_write <- list(
            "Chemical List"=out_chemicals
        )
        if(report_annotations == TRUE){
            data_to_write <- list(
                "Chemical List"=out_chemicals,
                "ADMET Binary Models"=topn_admet_binr,
                "ChEMBL Struc. Alerts"=topn_chembl,
                "Leadscope Models"=topn_leadscope,
                "OChem Struc. Alerts"=topn_ochem,
                "Opera ADME Models"=topn_opera_adme,
                "Opera Env. Fate Models"=topn_opera_environmental_fate,
                "Opera Physicochem. Models"=topn_opera_physicochem,
                "Opera Struc. Properties"=topn_opera_structural_properties,
                "Opera Tox. Endpoints"=topn_opera_toxicology_endpoints,
                "Saagar Descriptors"=topn_saagar,
                "CTD Bioprocess"=topn_ctd_bioprocess,
                "CTD Cellcomp."=topn_ctd_cellcomp,
                "CTD Diseases"=topn_ctd_diseases,
                "CTD Genes"=topn_ctd_genes,
                "CTD Molfunc."=topn_ctd_molfunct,
                "CTD Phenotypes"=topn_ctd_phenotypes,
                "ICE Assays"=topn_ice,
                "T3DB Targets"=topn_t3db,
                "ToxRefDB Neoplastic"=topn_toxrefdb_neoplastic,
                "ToxRefDB Non-neoplastic"=topn_toxrefdb_nonneoplastic,
                "HMDB Biospecimen Loc."=topn_hmdb_biospecimenlocations,
                "HMDB Cellular Loc."=topn_hmdb_cellularlocations,
                "HMDB Diseases"=topn_hmdb_diseases,
                "HMDB Genes"=topn_hmdb_genes,
                "HMDB Tissue Loc."=topn_hmdb_tissuelocations,
                "CPD Products"=topn_cpd,
                "DrugBank ATC Codes"=topn_drugbank_atccodes,
                "DrugBank Carriers"=topn_drugbank_carriers,
                "DrugBank Enzymes"=topn_drugbank_enzymes,
                "DrugBank Targets"=topn_drugbank_targets,
                "DrugBank Transporters"=topn_drugbank_transporters,
                "InVitroDB Assays"=topn_invitrodb,
                "PubChem Bioassays"=topn_pubchem,
                "PubChem Phys. Props."=topn_pubchem_props,
                "GRAS Safety Recog. Studies"=topn_gras,
                "FooDB Enzymes"=topn_foodb_enzymes,
                "FooDB Flavors"=topn_foodb_flavors,
                "FooDB Food Content"=topn_foodb_foodcontent,
                "FooDB Health Effects"=topn_foodb_healtheffects,
                "FooDB Ontology"=topn_foodb_ontology,
                "EPA Phys. Props."=topn_epa_props
            )
        }
        
        for(sheet in names(data_to_write)){
            addWorksheet(wb, sheet)
            
            if(nrow(data_to_write[[sheet]]) > 0){
                writeDataTable(wb, sheet, x=data_to_write[[sheet]], startCol=1, startRow=1)
                # Special per sheet formatting
                if(sheet == "Cluster Information"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 6, 7, 8),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "Chemical List"){
                    img_i <- 2
                    for(struc_img in struc_images){
                        insertImage(wb, sheet, file=struc_img, startRow=img_i, startCol=12, width=1, height=1)
                        img_i <- img_i + 1
                    }
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 2, 4, 5, 11, 12),
                        widths=c(20, 100, 100, 100, 100, 20)
                    )
                    if(report_images == TRUE){
                        setRowHeights(
                            wb,
                            sheet,
                            rows=seq(2, nrow(data_to_write[[sheet]])),
                            heights=unlist(lapply(seq(2, nrow(data_to_write[[sheet]])), function(x) 100))
                        )
                    }
                } else if(sheet == "ADMET Binary Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6),
                        widths=c(20, 20, 20, 200)
                    )
                } else if(sheet == "Leadscope Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6),
                        widths=c(20, 20, 20, 100)
                    )
                } else if(sheet == "OChem Struc. Alerts"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "Opera ADME Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 100)
                    )
                } else if(sheet == "Opera Env. Fate Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 200)
                    )
                } else if(sheet == "Opera Physicochem. Models"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 200)
                    )
                } else if(sheet == "Opera Struc. Properties"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 100)
                    )
                } else if(sheet == "Opera Tox. Endpoints"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7),
                        widths=c(20, 20, 20, 20, 200)
                    )
                } else if(sheet == "Saagar Descriptors"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "Saagar Descriptors"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Bioprocess"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Cellcomp."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Diseases"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5, 6),
                        widths=c(20, 20, 20, 20, 20)
                    )
                } else if(sheet == "CTD Genes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 7, 8, 9),
                        widths=c(20, 20, 20, 20, 20, 20)
                    )
                } else if(sheet == "CTD Molfunc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CTD Phenotypes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 6, 7, 8, 9, 10),
                        widths=c(20, 20, 20, 20, 20, 20, 20, 20)
                    )
                } else if(sheet == "ICE Assays"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 4, 5, 21, 22),
                        widths=c(20, 20, 20, 20, 20)
                    )
                } else if(sheet == "T3DB Targets"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "ToxRefDB Neoplastic"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "ToxRefDB Non-neoplastic"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Biospecimen Loc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Cellular Loc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Diseases"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Genes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "HMDB Tissue Loc."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "CPD Products"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank ATC Codes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "DrugBank Carriers"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank Enzymes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank Targets"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "DrugBank Transporters"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "InVitroDB Assays"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "PubChem Bioassays"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "PubChem Phys. Props."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                } else if(sheet == "GRAS Safety Recog. Studies"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Enzymes"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Flavors"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Food Content"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Health Effects"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "FooDB Ontology"){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4, 5),
                        widths=c(20, 20, 20, 20)
                    )
                } else if(sheet == "EPA Phys. Props."){
                    setColWidths(
                        wb,
                        sheet,
                        cols=c(1, 3, 4),
                        widths=c(20, 20, 20)
                    )
                }
            }
        }
        return(wb)
    })
}